removed karaf bundles, configs and features release numbers
Cognifide/aet-cookbook pull request #29
Opened 2018-07-31 12:02 UTC by PhilBug

2018-08-01 09:45 UTC, malaskowski requested changes

2018-08-01 09:45 UTC, Skejven commented on metadata.rb
> +version           '4.0.3'
Latest version is 4.0.1, please leave the old version (`4.0.2-SNAPSHOT`). It will be bumped when new version is released.

2018-08-01 09:46 UTC, malaskowski reviewed
Please update the `CHANGELOG`.

2018-08-02 10:52 UTC, wiiitek requested changes
The links to *version folders* are required for cookbook to recognize if deployed AET version has changed.

So that it knows if new artifacts should be downloaded for AETs. Do we really want to download them every time? Please consult with @karoldrazek  or  @jwadolowski

2018-08-27 12:24 UTC, closed without merging