Configurable browsermob proxy port range
Cognifide/aet-cookbook pull request #39
Opened 2018-09-20 14:22 UTC by tkaik

Browsermob proxy port range can now be configured by `['aet']['browsermob']['proxy_port_range']` attribute. 

According to [Browsermob docs](https://github.com/lightbody/browsermob-proxy#command-line-arguments), the default range is `(8081)-(8581)`

2018-09-20 14:44 UTC, malaskowski approved these changes

2018-09-22 19:49 UTC, wiiitek commented
Please also update cookbook version. I believe that as this is backward-comatibe change minor number should be incremented. Cheers!

2018-09-22 19:50 UTC, wiiitek requested changes
Please update cookbook versions

2018-10-10 08:36 UTC, PhilBug approved these changes

2018-10-11 07:27 UTC, wiiitek approved these changes

2018-10-17 09:49 UTC, merged